version: '3.1'

services:
  postgres:
    image: postgres:latest
    ports:
      -  '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: app
      POSTGRES_PASSWORD: qwerty123